//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svekla.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Svekla.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password rejected by Redis Server!.
        /// </summary>
        internal static string RBF_AccessDenied {
            get {
                return ResourceManager.GetString("RBF_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server address cannot be empty!.
        /// </summary>
        internal static string RBF_AddressEmpty {
            get {
                return ResourceManager.GetString("RBF_AddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server address!.
        /// </summary>
        internal static string RBF_AddressInvalid {
            get {
                return ResourceManager.GetString("RBF_AddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string RBF_Connect {
            get {
                return ResourceManager.GetString("RBF_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string RBF_Connecting {
            get {
                return ResourceManager.GetString("RBF_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with Redis server was interrupted!
        ///Pussible reasons:
        /// - Server machine ping timeout
        /// - Client received unexpected data
        /// - Client connection was killed.
        /// </summary>
        internal static string RBF_ConnectionInterrupted {
            get {
                return ResourceManager.GetString("RBF_ConnectionInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown connection error: {0}.
        /// </summary>
        internal static string RBF_ErrHostError {
            get {
                return ResourceManager.GetString("RBF_ErrHostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection timeout.
        /// </summary>
        internal static string RBF_ErrHostTimeout {
            get {
                return ResourceManager.GetString("RBF_ErrHostTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string RBF_Error {
            get {
                return ResourceManager.GetString("RBF_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redis server connection timeout.
        /// </summary>
        internal static string RBF_ErrRedisTimeout {
            get {
                return ResourceManager.GetString("RBF_ErrRedisTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled by user.
        /// </summary>
        internal static string RBF_ErrUserCancel {
            get {
                return ResourceManager.GetString("RBF_ErrUserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patience, man, patience....
        /// </summary>
        internal static string RBF_LP25 {
            get {
                return ResourceManager.GetString("RBF_LP25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re half way through!.
        /// </summary>
        internal static string RBF_LP50 {
            get {
                return ResourceManager.GetString("RBF_LP50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come on, it&apos;s almost done!.
        /// </summary>
        internal static string RBF_LP75 {
            get {
                return ResourceManager.GetString("RBF_LP75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just one last push!!!.
        /// </summary>
        internal static string RBF_LP90 {
            get {
                return ResourceManager.GetString("RBF_LP90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Key List....
        /// </summary>
        internal static string RBF_ProgressDwnKeys {
            get {
                return ResourceManager.GetString("RBF_ProgressDwnKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Key Information ({0}/{1})....
        /// </summary>
        internal static string RBF_ProgressGetInfo {
            get {
                return ResourceManager.GetString("RBF_ProgressGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}:{1} (Ping: {2}ms).
        /// </summary>
        internal static string RBF_TitleConnected {
            get {
                return ResourceManager.GetString("RBF_TitleConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
